### ISSUE TITLE
specify php version compat

### ISSUE THREAD

**Issue by SebSept** [Kaudaj/prestashop-maker#1]
**Is your feature request related to a problem? Please describe.**
does not install en php 7.2

**Describe the solution you'd like**
just have the info on the README ;) 

**Describe alternatives you've considered**
none

**Additional context**
first try

**Comment by Kaudaj** [comment]
Thanks for the report!
I'm currently working on the README so I'll add this in the day.

**Comment by Kaudaj** [comment]
Should now be fixed by https://github.com/Kaudaj/prestashop-maker/commit/b07a2595d40828a8c109ab5fcc65cb500f65a5ca!
